### ISSUE TITLE
Erro ao rodar comando s2n

### ISSUE THREAD

**Issue by danemmanuel** [danielbonifacio/s2n#9]
![image](https://user-images.githubusercontent.com/20229516/67483267-d3e4c780-f63b-11e9-83aa-8cf65e833209.png)

**Comment by danielbonifacio** [comment]
Poderia me informar a versão do node?

**Comment by danemmanuel** [comment]
10.16.0

**Comment by danemmanuel** [comment]
Atualizei o node para a v13.3.0, porém quando tento rodar o s2n me retorna o seguinte erro
![image](https://user-images.githubusercontent.com/20229516/70236772-804abb00-175d-11ea-9b20-e7fdd6d13e38.png)

**Comment by danielbonifacio** [comment]
@danemmanuel O erro de timeout pode ter ocorrido por uma instabilidade na rede ou servidores do [swagger.io](https://swagger.io). Consegue fazer um teste usando a mesma versão do node com acesso a rede?
